version: "2"

build:
  os: "ubuntu-24.04"
  apt_packages:
    - libgirepository-2.0-dev
    - gobject-introspection
    - libcairo2-dev
    - build-essential
    - gir1.2-gtk-3.0
    - python3-gi
    - python3-gi-cairo
  tools:
    python: "3.13"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
      - dev

sphinx:
  configuration: docs/source/conf.py