site_name: PyonFX

site_description: >
  PyonFX documentation.

site_author: CoffeeStraw
copyright: Copyright &copy; 2019-2025 Antonio Strippoli (CoffeeStraw) and <a href="https://github.com/CoffeeStraw/PyonFX/graphs/contributors"><u>contributors</u></a>

repo_url: https://github.com/CoffeeStraw/PyonFX
repo_name: CoffeeStraw/PyonFX

theme:
  name: material
  language: en
  favicon: static/favicon.ico
  logo: static/logo.png
  features:
    - navigation.sections
    - navigation.footer
    - content.footnote.tooltips
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            group_by_category: true
            members_order: source
  - tags

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Tutorials:
      - "Install & Set-up": tutorials/installing.md
      - "Structured objects": tutorials/structured_objects.md
  - Guides:
      - "TBD": guides/tbd.md
  - Reference:
      - "Module index": reference/index.md
      - "ass_core": reference/ass_core.md
      - "convert": reference/convert.md
      - "font": reference/font.md
      - "pixel": reference/pixel.md
      - "shape": reference/shape.md
      - "utils": reference/utils.md
  - Explanation:
      - "TBD": explanation/tbd.md